# This file is covered by the LICENSE file in the root of this project.
labels:
  0: "unlabeled"
  1: "outlier"
  2: "outlier"
  8: "outlier"
  17: "outlier"
  10: "car"
  11: "bicycle"
  13: "bus"
  15: "motorcycle"
  16: "on-rails"
  18: "truck"
  20: "other-vehicle"
  30: "person"
  31: "bicyclist"
  32: "motorcyclist"
  40: "road"
  44: "parking"
  48: "sidewalk"
  49: "other-ground"
  50: "building"
  51: "fence"
  52: "other-structure"
  60: "lane-marking"
  70: "vegetation"
  71: "trunk"
  72: "terrain"
  80: "pole"
  81: "traffic-sign"
  99: "other-object"
  252: "moving-car"
  253: "moving-bicyclist"
  254: "moving-person"
  255: "moving-motorcyclist"
  256: "moving-on-rails"
  257: "moving-bus"
  258: "moving-truck"
  259: "moving-other-vehicle"
color_map: # bgr
  0: [ 0, 0, 0 ]
  1: [ 0, 0, 255 ]
  2: [ 245, 150, 100 ]
  3: [ 245, 230, 100 ]
  4: [ 250, 80, 100 ]
  5: [ 150, 60, 30 ]
  6: [ 255, 0, 0 ]
  7: [ 180, 30, 80 ]
  8: [ 255, 0, 0 ]
  9: [ 30, 30, 255 ]
  10: [ 200, 40, 255 ]
  11: [ 90, 30, 150 ]
  12: [ 255, 0, 255 ]
  13: [ 255, 150, 255 ]
  14: [ 75, 0, 75 ]
  15: [ 75, 0, 175 ]
  16: [ 0, 200, 255 ]
  17: [ 50, 120, 255 ]
  18: [ 0, 150, 255 ]
  19: [ 170, 255, 150 ]
  20: [ 0, 175, 0 ]
  21: [ 0, 60, 135 ]
  22: [ 80, 240, 150 ]

content: # as a ratio with the total number of points
  0: 1.018889854628292943
  1: 1.0002937197336781505
  2: 1.1326861944777486
  3: 1.0723592229456223
  4: 1.1987493871255525
  5: 1.014717169549888214
  6: 1.14392298360372
  7: 1.14392298360372
  8: 1.14392298360372
  9: 1.0039048553037472045
  10: 1.040818519255974316
  11: 1.00016609538710764618
  12: 1.00016609538710764618
  13: 1.0027879693665067774
  14: 1.0027879693665067774
  15: 1.00039838616015114444
  16: 1.0020633612104619787
  17: 1.0020633612104619787
  18: 1.0020633612104619787
  19: 1.0020633612104619787
  20: 1.0016218197275284021
  21: 1.0020633612104619787
  22: 1.0016218197275284021

# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0     # "unlabeled"
  1: 0     # "outlier"
  10: 1 # "Car"
  18: 6 # "Truck"
  13: 4 # "Bus"
  20: 4 # "Other Vehicle"
  32: 3 # "Motorcyclist"
  31: 2 # "Bicyclist"
  30: 5 # "Pedestrian"
  8: 11 # "Sign"
  81: 11 # "Traffic Light"
  80: 11 # "Pole"
  72: 11 # "Construction Cone"
  11: 2 # "Bicycle"
  15: 3 # "Motorcycle"
  50: 11 # "Building"
  70: 10 # "Vegetation"
  71: 11 # "Tree Trunk"
  17: 7 # "Curb"
  40: 7 # "Road"
  60: 7 # "Lane Marker"
  44: 9 # "Walkable"
  48: 8 # "Sidewalk"
  49: 9 # "Other Ground"
  16: 4     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  51: 11    # "fence"
  52: 0     # "other-structure" mapped to "unlabeled" ------------------mapped
  99: 0     # "other-object" to "unlabeled" ----------------------------mapped
  252: 1    # "moving-car" to "car" ------------------------------------mapped
  253: 2    # "moving-bicyclist" to "bicyclist" ------------------------mapped
  254: 5    # "moving-person" to "person" ------------------------------mapped
  255: 3    # "moving-motorcyclist" to "motorcyclist" ------------------mapped
  256: 4    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  257: 4    # "moving-bus" mapped to "other-vehicle" -------------------mapped
  258: 6    # "moving-truck" to "truck" --------------------------------mapped
  259: 4    # "moving-other"-vehicle to "other-vehicle" ----------------mapped

learning_map_inv: # inverse of previous map
  0: 0 #: 0     # "unlabeled"
  1: 10 #: 1 # "Car"
  2: 15 #: 2 # "motorcycle"
  3: 11 #: 3 # "bicycle"
  4: 20 #: 4 # "o-vehicle"
  5: 30 #: 5 # "pedestrian"
  6: 18 #: 6 # "truck"
  7: 40 #: 7 # "Drivable-area"
  8: 48 #: 8 # "Sidewalk"
  9: 72 #: 9 # "Terrain"
  10: 70 #: 10 # "vegitation"
  11: 50 #: 11 # "Manmade"


learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False #: 1 # "Car"
  2: False #: 2 # "motorcycle"
  3: False #: 3 # "bicycle"
  4: False #: 4 # "o-vehicle"
  5: False #: 5 # "pedestrian"
  6: False #: 6 # "truck"
  7: False #: 7 # "Drivable-area"
  8: False #: 8 # "Sidewalk"
  9: False #: 9 # "Terrain"
  10: False #: 10 # "vegitation"
  11: False #: 11 # "Manmade"


split: # sequence numbers
  train:
    - '00'
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    - '07'
    - '09'
    - '10'

  valid:
    - '08'

  pseudo:
    - '11'

  test:
    - '11'
    - '12'
    - '13'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '20'
    - '21'
