# This file is covered by the LICENSE file in the root of this project.
labels:
  0: "Undefined"
  1: "Car"
  2: "Truck"
  3: "Bus"
  4: "Other Vehicle" # Other small vehicles (e.g. pedicab) and large vehicles (e.g. construction vehicles, RV, limo, tram).
  5: "Motorcyclist"
  6: "Bicyclist"
  7: "Pedestrian"
  8: "Sign"
  9: "Traffic Light"
  10: "Pole" # Lamp post, traffic sign pole etc.
  11: "Construction Cone" # Construction cone/pole.
  12: "Bicycle"
  13: "Motorcycle"
  14: "Building"
  15: "Vegetation" # Bushes, tree branches, tall grasses, flowers etc.
  16: "Tree Trunk"
  17: "Curb" # Curb on the edge of roads. This does not include road boundaries if there’s no curb.
  18: "Road" # Surface a vehicle could drive on. This include the driveway connecting // parking lot and road over a section of sidewalk.
  19: "Lane Marker" # Marking on the road that’s specifically for defining lanes such as // single/double white/yellow lines.
  20: "Other Ground" # Marking on the road other than lane markers, bumps, cateyes, railtracks // etc.
  21: "Walkable" # Most horizontal surface that’s not drivable, e.g. grassy hill, // pedestrian walkway stairs etc.
  22: "Sidewalk" # Nicely paved walkable surface when pedestrians most likely to walk on.

color_map: # bgr
  0: [ 0, 0, 0 ]
  1: [ 0, 0, 255 ]
  2: [ 245, 150, 100 ]
  3: [ 245, 230, 100 ]
  4: [ 250, 80, 100 ]
  5: [ 150, 60, 30 ]
  6: [ 255, 0, 0 ]
  7: [ 180, 30, 80 ]
  8: [ 255, 0, 0 ]
  9: [ 30, 30, 255 ]
  10: [ 200, 40, 255 ]
  11: [ 90, 30, 150 ]
  12: [ 255, 0, 255 ]
  13: [ 255, 150, 255 ]
  14: [ 75, 0, 75 ]
  15: [ 75, 0, 175 ]
  16: [ 0, 200, 255 ]
  17: [ 50, 120, 255 ]
  18: [ 0, 150, 255 ]
  19: [ 170, 255, 150 ]
  20: [ 0, 175, 0 ]
  21: [ 0, 60, 135 ]
  22: [ 80, 240, 150 ]

content: # as a ratio with the total number of points
  0: 1.018889854628292943
  1: 1.0002937197336781505
  2: 1.1326861944777486
  3: 1.0723592229456223
  4: 1.1987493871255525
  5: 1.014717169549888214
  6: 1.14392298360372
  7: 1.14392298360372
  8: 1.14392298360372
  9: 1.0039048553037472045
  10: 1.040818519255974316
  11: 1.00016609538710764618
  12: 1.00016609538710764618
  13: 1.0027879693665067774
  14: 1.0027879693665067774
  15: 1.00039838616015114444
  16: 1.0020633612104619787
  17: 1.0020633612104619787
  18: 1.0020633612104619787
  19: 1.0020633612104619787
  20: 1.0016218197275284021
  21: 1.0020633612104619787
  22: 1.0016218197275284021

# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0     # "unlabeled"
  1: 1     # "car"
  12: 2     # "bicycle"
  3: 5     # "bus" mapped to "other-vehicle" --------------------------mapped
  13: 3     # "motorcycle"
  2: 4     # "truck"
  4: 5     # "other-vehicle"
  7: 6     # "person"
  6: 7     # "bicyclist"
  5: 8     # "motorcyclist"
  18: 9     # "road"
  21: 10    # "parking"
  22: 11    # "sidewalk"
  20: 12    # "other-ground"
  14: 13    # "building"
  9: 14    # "fence"
  11: 0     # "other-structure" mapped to "unlabeled" ------------------mapped
  19: 9     # "lane-marking" to "road" ---------------------------------mapped
  15: 15    # "vegetation"
  16: 16    # "trunk"
  17: 17    # "terrain"
  10: 18    # "pole"
  8: 19    # "traffic-sign"

learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 1     # "car"
  2: 12     # "bicycle"
  3: 13     # "motorcycle"
  4: 2     # "truck"
  5: 4     # "other-vehicle"
  6: 7     # "person"
  7: 6     # "bicyclist"
  8: 5     # "motorcyclist"
  9: 18     # "road"
  10: 21    # "parking"
  11: 22    # "sidewalk"
  12: 20    # "other-ground"
  13: 14    # "building"
  14: 9    # "fence"
  15: 15    # "vegetation"
  16: 16    # "trunk"
  17: 17    # "terrain"
  18: 10    # "pole"
  19: 8    # "traffic-sign"

learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "motorcycle"
  4: False     # "truck"
  5: False     # "other-vehicle"
  6: False     # "person"
  7: False     # "bicyclist"
  8: False     # "motorcyclist"
  9: False     # "road"
  10: False    # "parking"
  11: False    # "sidewalk"
  12: False    # "other-ground"
  13: False    # "building"
  14: False    # "fence"
  15: False    # "vegetation"
  16: False    # "trunk"
  17: False    # "terrain"
  18: False    # "pole"
  19: False    # "traffic-sign"

split: # sequence numbers
  train: # 40 percent gt
    - 00
    - 01
    - 02
    - 03
    - 04
    - 05
    - 06
    - 07
    - 09
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  valid:
    - 8
  test: # 60 percent psl
    - 00
    - 01
    - 02
    - 03
    - 04
    - 05
    - 06
    - 07
    - 09
    - 10
