# This file is covered by the LICENSE file in the root of this project.
labels:
  0: "unlabeled"
  1: "outlier"
  2: "outlier"
  8: "outlier"
  17: "outlier"
  10: "car"
  11: "bicycle"
  13: "bus"
  15: "motorcycle"
  16: "on-rails"
  18: "truck"
  20: "other-vehicle"
  30: "person"
  31: "bicyclist"
  32: "motorcyclist"
  40: "road"
  44: "parking"
  48: "sidewalk"
  49: "other-ground"
  50: "building"
  51: "fence"
  52: "other-structure"
  60: "lane-marking"
  70: "vegetation"
  71: "trunk"
  72: "terrain"
  80: "pole"
  81: "traffic-sign"
  99: "other-object"
  252: "moving-car"
  253: "moving-bicyclist"
  254: "moving-person"
  255: "moving-motorcyclist"
  256: "moving-on-rails"
  257: "moving-bus"
  258: "moving-truck"
  259: "moving-other-vehicle"
color_map: # bgr
  0: [ 0, 0, 0 ]
  1: [ 0, 0, 255 ]
  2: [ 245, 150, 100 ]
  3: [ 245, 230, 100 ]
  4: [ 250, 80, 100 ]
  5: [ 150, 60, 30 ]
  6: [ 255, 0, 0 ]
  7: [ 180, 30, 80 ]
  8: [ 255, 0, 0 ]
  9: [ 30, 30, 255 ]
  10: [ 200, 40, 255 ]
  11: [ 90, 30, 150 ]
  12: [ 255, 0, 255 ]
  13: [ 255, 150, 255 ]
  14: [ 75, 0, 75 ]
  15: [ 75, 0, 175 ]
  16: [ 0, 200, 255 ]
  17: [ 50, 120, 255 ]
  18: [ 0, 150, 255 ]
  19: [ 170, 255, 150 ]
  20: [ 0, 175, 0 ]
  21: [ 0, 60, 135 ]
  22: [ 80, 240, 150 ]

content: # as a ratio with the total number of points
  0: 1.018889854628292943
  1: 1.0002937197336781505
  2: 1.1326861944777486
  3: 1.0723592229456223
  4: 1.1987493871255525
  5: 1.014717169549888214
  6: 1.14392298360372
  7: 1.14392298360372
  8: 1.14392298360372
  9: 1.0039048553037472045
  10: 1.040818519255974316
  11: 1.00016609538710764618
  12: 1.00016609538710764618
  13: 1.0027879693665067774
  14: 1.0027879693665067774
  15: 1.00039838616015114444
  16: 1.0020633612104619787
  17: 1.0020633612104619787
  18: 1.0020633612104619787
  19: 1.0020633612104619787
  20: 1.0016218197275284021
  21: 1.0020633612104619787
  22: 1.0016218197275284021

# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0     # "unlabeled"
  1: 0     # "outlier"
  10: 1 # "Car"
  18: 2 # "Truck"
  13: 3 # "Bus"
  20: 4 # "Other Vehicle"
  32: 5 # "Motorcyclist"
  31: 6 # "Bicyclist"
  30: 7 # "Pedestrian"
  8: 8 # "Sign"
  81: 9 # "Traffic Light"
  80: 10 # "Pole"
  72: 11 # "Construction Cone"
  11: 12 # "Bicycle"
  15: 13 # "Motorcycle"
  50: 14 # "Building"
  70: 15 # "Vegetation"
  71: 16 # "Tree Trunk"
  17: 17 # "Curb"
  40: 18 # "Road"
  60: 19 # "Lane Marker"
  44: 20 # "Walkable"
  48: 21 # "Sidewalk"
  49: 22 # "Other Ground"
  16: 4     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  51: 14    # "fence"
  52: 0     # "other-structure" mapped to "unlabeled" ------------------mapped
  99: 0     # "other-object" to "unlabeled" ----------------------------mapped
  252: 1    # "moving-car" to "car" ------------------------------------mapped
  253: 6    # "moving-bicyclist" to "bicyclist" ------------------------mapped
  254: 7    # "moving-person" to "person" ------------------------------mapped
  255: 5    # "moving-motorcyclist" to "motorcyclist" ------------------mapped
  256: 4    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  257: 3    # "moving-bus" mapped to "other-vehicle" -------------------mapped
  258: 2    # "moving-truck" to "truck" --------------------------------mapped
  259: 4    # "moving-other"-vehicle to "other-vehicle" ----------------mapped

learning_map_inv: # inverse of previous map
  0: 0 #: 0     # "unlabeled"
  1: 10 #: 1 # "Car"
  2: 18 #: 2 # "Truck"
  3: 13 #: 3 # "Bus"
  4: 20 #: 4 # "Other Vehicle"
  5: 32 #: 5 # "Motorcyclist"
  6: 31 #: 6 # "Bicyclist"
  7: 30 #: 7 # "Pedestrian"
  8: 2 #: 8 # "Sign"
  9: 81 #: 9 # "Traffic Light"
  10: 80 #: 10 # "Pole"
  11: 72 #: 11 # "Construction Cone"
  12: 11 #: 12 # "Bicycle"
  13: 15 #: 13 # "Motorcycle"
  14: 50 #: 14 # "Building"
  15: 70  # "Vegetation"
  16: 71  # "Tree Trunk"
  17: 17 # "Curb"
  18: 40 # "Road"
  19: 60 # "Lane Marker"
  20: 44 # "Walkable"
  21: 48 # "Sidewalk"
  22: 49 # "Other Ground"

learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "motorcycle"
  4: False     # "truck"
  5: False     # "other-vehicle"
  6: False     # "person"
  7: False     # "bicyclist"
  8: False     # "motorcyclist"
  9: False     # "road"
  10: False    # "parking"
  11: False    # "sidewalk"
  12: False    # "other-ground"
  13: False    # "building"
  14: False    # "fence"
  15: False    # "vegetation"
  16: False    # "trunk"
  17: False    # "terrain"
  18: False    # "pole"
  19: False    # "traffic-sign"
  20: False    # "traffic-sign"
  21: False    # "traffic-sign"
  22: False    # "traffic-sign"

split: # sequence numbers
  train:
    - '00'
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    - '07'
    - '09'
    - '10'

  valid:
    - '08'

  pseudo:
    - '11'

  test:
    - '11'
    - '12'
    - '13'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '20'
    - '21'
