# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 23
  num_input_features: 16
  use_norm: True
  init_size: 32

###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "WOD_multiscan" #  #  # "SemKITTI_sk" #
  ignore_label: 0 # undefined
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/wod/wod-multiscan_labelled.yaml"
  max_volume_space:
    - 100 #50
    - 3.1415926
    - 4
  min_volume_space:
    - 0
    - -3.1415926
    - -2

###################
## Data_loader options
train_data_loader:
  data_path: "/mnt/beegfs/gpu/argoverse-tracking-all-training/WOD/processed/Labeled_32_beam/training"
  imageset: "train"
  return_ref: True
  batch_size: 3 #4
  shuffle: True
  num_workers: 0

val_data_loader:
  data_path: "/mnt/beegfs/gpu/argoverse-tracking-all-training/WOD/processed/Labeled_32_beam/validation"
  imageset: "val"
  return_ref: True
  batch_size: 3
  shuffle: False
  num_workers: 0
  
test_data_loader:
  data_path: "/mnt/beegfs/gpu/argoverse-tracking-all-training/WOD/processed/Unlabeled/testing"
  imageset: "test"
  return_ref: True
  batch_size: 4
  shuffle: False
  num_workers: 4

ssl_data_loader:
  data_path: "/mnt/beegfs/gpu/argoverse-tracking-all-training/WOD/processed/Unlabeled/testing"
  imageset: "pseudo"
  return_ref: True
  batch_size: 2
  shuffle: False
  num_workers: 4


###################
## test params
train_params:
  model_load_path: "/home/gebreawe/Model_checkpoint/Segmentation/ST-UDA/model_save_dir/wod_save_f0_0_32beam_time.pt"
  model_save_path: "/home/gebreawe/Model_checkpoint/Segmentation/ST-UDA/model_save_dir/wod_save_f0_0_32beam_time.pt"
  checkpoint_every_n_steps: 1000
  max_num_epochs: 40
  eval_every_n_steps: 1000
  learning_rate: 0.001
  past: 0
  future: 0
  T_past: 032
  T_future: 032
  ssl: False
  rgb: False  
  uda: False
  time: True