# This file is covered by the LICENSE file in the root of this project.
labels:
  0: "Undefined"
  1: "vehicle"
  2: "person"
  3: "road"
  4: "sidewalk"
  5: "terrain"
  6: "man-made"
  7: "vegetation"

color_map: # bgr
  0: [ 0, 0, 0 ]
  1: [ 0, 0, 255 ]
  2: [ 245, 150, 100 ]
  3: [ 245, 230, 100 ]
  4: [ 250, 80, 100 ]
  5: [ 150, 60, 30 ]
  6: [ 255, 0, 0 ]
  7: [ 180, 30, 80 ]
  8: [ 255, 0, 0 ]
  9: [ 30, 30, 255 ]
  10: [ 200, 40, 255 ]
  11: [ 90, 30, 150 ]
  12: [ 255, 0, 255 ]
  13: [ 255, 150, 255 ]
  14: [ 75, 0, 75 ]
  15: [ 75, 0, 175 ]
  16: [ 0, 200, 255 ]
  17: [ 50, 120, 255 ]
  18: [ 0, 150, 255 ]
  19: [ 170, 255, 150 ]
  20: [ 0, 175, 0 ]
  21: [ 0, 60, 135 ]
  22: [ 80, 240, 150 ]

content: # as a ratio with the total number of points
  0: 1.018889854628292943
  1: 1.0002937197336781505
  2: 1.1326861944777486
  3: 1.0723592229456223
  4: 1.1987493871255525
  5: 1.014717169549888214
  6: 1.14392298360372
  7: 1.14392298360372


# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0 : 0     # "unlabeled"
  1 : 0     # "outlier" mapped to "unlabeled" --------------------------mapped
  10: 1     # "car"
  11: 0     # "bicycle"
  13: 0     # "bus" mapped to "other-vehicle" --------------------------mapped
  15: 0     # "motorcycle"
  16: 0     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  18: 0     # "truck"
  20: 0     # "other-vehicle"
  30: 2     # "person"
  31: 0     # "bicyclist"
  32: 0     # "motorcyclist"
  40: 3     # "road"
  44: 3    # "parking"
  48: 4    # "sidewalk"
  49: 0    # "other-ground"
  50: 6    # "building"
  51: 6    # "fence"
  52: 0     # "other-structure" mapped to "unlabeled" ------------------mapped
  60: 3     # "lane-marking" to "road" ---------------------------------mapped
  70: 7    # "vegetation"
  71: 7    # "trunk"
  72: 5    # "terrain"
  80: 6    # "pole"
  81: 6    # "traffic-sign"
  99: 0     # "other-object" to "unlabeled" ----------------------------mapped
  252: 1    # "moving-car" to "car" ------------------------------------mapped
  253: 0    # "moving-bicyclist" to "bicyclist" ------------------------mapped
  254: 2    # "moving-person" to "person" ------------------------------mapped
  255: 0    # "moving-motorcyclist" to "motorcyclist" ------------------mapped
  256: 0    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  257: 0    # "moving-bus" mapped to "other-vehicle" -------------------mapped
  258: 0    # "moving-truck" to "truck" --------------------------------mapped
  259: 0    # "moving-other"-vehicle to "other-vehicle" ----------------mapped
learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 10     # "vehicle"
  2: 30     # "person"
  3: 40     # "road"
  4: 48     # "sidewalk"
  5: 72     # "terrain"
  6: 50     # "man-made"
  7: 70     # "vegetation"

learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "vehicle"
  2: False     # "person"
  3: False     # "road"
  4: False     # "sidewalk"
  5: False     # "terrain"
  6: False     # "man-made"
  7: False     # "vegetation"

split: # sequence numbers
  train:
    - '00'
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    - '07'
    - '09'
    - '10'

  valid:
    - '08'

  pseudo:
    - '11'

  test: #
    - '11'
    - '12'
    - '13'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '20'
    - '21'
