# This file is covered by the LICENSE file in the root of this project.
labels:
  0: 'noise'
  1: 'building'
  2: 'fences'
  3: 'other'
  4: 'pedestrian'
  5: 'pole'
  6: 'roadlines'
  7: 'road'
  8: 'sidewalk'
  9: 'vegeation'
  10: 'vehicle'
  11: 'wall'
  12: 'trafficsing'
  13: 'sky'
  14: 'ground'
  15: 'bridge'
  16: 'railtrack'
  17: 'guardrail'
  18: 'trafficlight'
  19: 'static'
  20: 'dynamic'
  21: 'water'
  22: 'terrain'

# content: # as a ratio with the total number of points
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0
  1: 6 # manmade
  2: 6 # fence  --> mapped to "manmade"
  3: 0 # other  --> mapped to "undefined"
  4: 2 # pedestrian
  5: 6 # pole
  6: 3 # roadlines  --> mapped to "road"
  7: 3 # road
  8: 4 # sidewalk  --> mapped to "road"
  9: 7 # vegetation
  10: 1 # vehicle/car
  11: 6 # wall  --> mapped to "manmade"
  12: 6 # trafficsign --> mapped to "sign"
  13: 0 # sky --> mapped to "undefined"
  14: 0 # grond  --> mapped to "road"
  15: 6 # bridge --> mapped to "manmade"
  16: 6 # railtrack  --> mapped to "manmade"
  17: 6 # guardrail --> mapped to "manmade"
  18: 0 # traficlight --> mapped to "sign"
  19: 0 # static --> mapped to "undefined"
  20: 0 # dynamic --> mapped to "undefined"
  21: 0 # water --> mapped to "undefined"
  22: 5 # terrain

learning_map_inv: # inverse of previous map
  0 : 0
  1 : 1
  2 : 4
  3 : 7
  4 : 8
  5 : 22
  6 : 1
  7 : 9

learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "vehicle"
  2: False     # "pedestrian"
  3: False     # "road"
  4: False     # "sidewalk"
  5: False     # "terrain"
  6: False     # "manmade"
  7: False     # "vegetation"

split: # sequence numbers
  train: # 20 percent gt
#  - 'Town06'
#  - 'Town07'
#  - 'Town10HD'
   - 'X5-MIA2662_TIC_PCAP_20210616_065116_HIL_output'

  valid: #
#  - 'Town06'
#  - 'Town07'
#  - 'Town10HD'
   - 'X5-MIA2662_TIC_PCAP_20210621_085330_HIL_output'
  pseudo: #
#  - 'Town06'
#  - 'Town07'
#  - 'Town10HD'
   - 'X5-MIA2662_TIC_PCAP_20210816_181912_HIL_output'

  test: #
#  - 'Town06'
#  - 'Town07'
#  - 'Town10HD'
   - 'X5-MIA2662_TIC_PCAP_20210816_183246_HIL_output'

#- 'X5-MIA2662_TIC_PCAP_20210616_065116_HIL_output'
#- 'X5-MIA2662_TIC_PCAP_20210621_085330_HIL_output'
#- 'X5-MIA2662_TIC_PCAP_20210816_181912_HIL_output'
#- 'X5-MIA2662_TIC_PCAP_20210816_182320_HIL_output'
#- 'X5-MIA2662_TIC_PCAP_20210816_182930_HIL_output'
#- 'X5-MIA2662_TIC_PCAP_20210816_183246_HIL_output'
#- 'X5-MIA2662_TIC_PCAP_20210816_183855_HIL_output'
