# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 15
  num_input_features: 16
  use_norm: True
  init_size: 32

###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "WOD_multiscan" #  #  # "SemKITTI_sk" #
  ignore_label: 0 # undefined
  return_test: False
  fixed_volume_space: True
  label_mapping: "./configs/label_mapping/da_livox_sim_real/livox.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 4
  min_volume_space:
    - 0
    - -3.1415926
    - -2

###################
## Data_loader options
train_data_loader:
  data_path: "/mnt/personal/gebreawe/Datasets/Synthetic/Valeo/Livox/processed"
  imageset: "train"
  return_ref: True
  batch_size: 4 #4
  shuffle: True
  num_workers: 0

val_data_loader:
  data_path: "/mnt/personal/gebreawe/Datasets/Synthetic/Valeo/Livox/processed"
  imageset: "val"
  return_ref: True
  batch_size: 4
  shuffle: False
  num_workers: 0

test_data_loader:
  data_path: "/mnt/personal/gebreawe/Datasets/RealWorld/Valeo/Livox/processed/Data_FC_2022_03_Honda_Jazz_full/city"
  imageset: "test"
  return_ref: True
  batch_size: 4
  shuffle: False
  num_workers: 4

ssl_data_loader:
  data_path: "/mnt/personal/gebreawe/Datasets/Synthetic/Valeo/Livox/processed"
  imageset: "pseudo"
  return_ref: True
  batch_size: 4
  shuffle: False
  num_workers: 4

###################
## test params
train_params:
  teacher_model_path: "/home/gebreawe/Model_checkpoint/Segmentation/T-UDA/model_save_dir/teacher_livoxsim_f0_0.pt"
  student_model_path: "/home/gebreawe/Model_checkpoint/Segmentation/T-UDA/model_save_dir/student_livoxsim_f0_0.pt"
  checkpoint_every_n_steps: 1000
  max_num_epochs: 40
  eval_every_n_steps: 1000
  learning_rate: 0.001
  past: 0
  future: 0
  T_past: '0_sim'
  T_future: '0'
  ssl: False
  rgb: False
  uda: True
  time: True
  S_sensor_zpose: -1.9
  T_sensor_zpose: -1.9
